version: '3.9'

name: my-microservices
services:
  auth-database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
      PGDATA: ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ${DATABASE_PGDATA}
    env_file:
      - .env
    networks:
      my-ms:

  auth-postgres-migration:
    container_name: auth-migrations
    build:
      context: .
    restart: on-failure
    depends_on:
      - auth-database
    volumes:
      - ./alembic.ini:/app/alembic.ini:ro
      - ./src_auth/infrastructure/database/migrations:/app/src_auth/infrastructure/database/migrations:ro
    command: ["python", "-m", "alembic", "upgrade", "head"]
    networks:
      my-ms:

  auth-fastapi-app:
    container_name: auth-web-app
    build: .
    command: python run_auth.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - auth-database
    restart: always
    env_file:
      - .env
    networks:
      my-ms:

networks:
  my-ms:
    driver: bridge
