version: '3'

services:

  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
      PGDATA: ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ${DATABASE_PGDATA}
    env_file:
      - .env

    postgres_migration:
    container_name: migrations
    build:
      context: .
    restart: on-failure
    depends_on:
      - database
    volumes:
      - ./alembic.ini:/app/alembic.ini:ro
      - ./src_auth/infrastructure/database/migrations:/app/src_auth/infrastructure/database/migrations:ro
    command: ["python", "-m", "alembic", "upgrade", "head"]
