"""update time_updated coulumn

Revision ID: 2886fafea9d6
Revises: ade66a311248
Create Date: 2023-06-01 20:52:54.287047

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2886fafea9d6"
down_revision = "ade66a311248"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "avatars", "time_updated", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "users", "time_updated", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "time_updated", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "avatars", "time_updated", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
