version: '3.7'

services:
  etcd:
    build: api_gateway/etcd
    restart: always
    command: bash etcd-setup.sh
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      apisix:

  apisix:
    build: api_gateway/apisix
    restart: always
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
