version: "3.9"

name: my-microservices
services:
  apisix:
    container_name: apisix.gateway
    build: api_gateway/apisix
    restart: always
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      my-ms:
    env_file:
      - .env

networks:
  my-ms:
    driver: bridge

volumes:
  etcd_data:
    driver: local
