version: '3'

services:

  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
      PGDATA: ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ${DATABASE_PGDATA}
    env_file:
      - .env
