apisix:
  node_listen: 9080 # APISIX listening port
  enable_ipv6: true # Enable IPv6 support
  enable_admin: true # Enable Admin API
  enable_server_tokens: true # Show APISIX version in the `Server` response header

etcd:
  host: # multiple etcd address
    - "http://127.0.0.1:2379"
  user: apisix # etcd username
  password: apisix # etcd password

admin:
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

proxy_cache:
  cache_ttl: 10s # The default caching time on disk if the upstream does not specify a caching time
  zones:
    - name: disk_cache_one # Name of the cache
      memory_size: 50m # Size of the memory to store the cache index
      disk_size: 1G # Size of the disk to store the cache data
      disk_path: /tmp/disk_cache_one # Path to the cache file for disk cache
      cache_levels: 1:2 # Cache hierarchy levels of disk cache
