"""delete column avatar_content

Revision ID: b414ea2023e2
Revises: 9b6ae67797c3
Create Date: 2023-06-05 21:02:07.250943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b414ea2023e2'
down_revision = '9b6ae67797c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'avatar_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'avatars',
        sa.Column(
            'avatar_content',
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=True
        )
    )
    # ### end Alembic commands ###
