FROM apache/apisix:3.3.0

# Copy custom config.yaml
COPY conf/config.yaml /usr/local/apisix/conf/config.yaml

# Copy custom apisix.yaml for standalone mode
COPY conf/apisix.yaml /usr/local/apisix/conf/apisix.yaml
