version: "3.9"

name: my-microservices
services:
  setup:
    profiles:
      - setup
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/configure_variables.sh:/configure_variables.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      my-ms:
    depends_on:
      - posts-elasticsearch

  posts-elasticsearch:
    container_name: posts-elasticsearch
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - ${ELASTIC_PORT:-}:${ELASTIC_PORT:-}
      - ${ELASTIC_TCP_PORT:-}:${ELASTIC_TCP_PORT:-}
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      my-ms:
    restart: unless-stopped
    env_file:
      - .env

  posts-kibana:
    container_name: posts-kibana
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - ${KIBANA_PORT:-}:${KIBANA_PORT:-}
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      my-ms:
    depends_on:
      - posts-elasticsearch
    restart: unless-stopped
    env_file:
      - .env

  posts-curator:
    container_name: posts-curator
    build:
      context: curator/
    command: --config ./.curator/curator.yml /.curator/create_post_index.yml
    volumes:
      - ./curator/config/curator.yml:/.curator/curator.yml:ro,Z
      - ./curator/config/create_post_index.yml:/.curator/create_post_index.yml:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      my-ms:
    depends_on:
      - posts-elasticsearch

  posts-fastapi-app:
    container_name: posts-web-app
    build: .
    command: python run_posts.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - posts-elasticsearch
    restart: always
    networks:
      my-ms:
    env_file:
      - .env

networks:
  my-ms:
    driver: bridge

volumes:
  elasticsearch:
    driver: local
