name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
      env:
        AUTH_SECRET_KEY: pass
        SITE_HOST: pass
        SITE_PORT: 0000
        DATABASE_USER: pass
        DATABASE_PASSWORD: pass
        DATABASE_DB: pass
        DATABASE_PGDATA: pass
        DATABASE_PORT: 0000
        DATABASE_HOST: pass
        ORM_ECHO_SETTINGS: True
        ORM_FUTURE_SETTINGS: pass # True
        ORM_POOL_SIZE_SETTINGS: 1
        MINIO_ROOT_USER: pass
        MINIO_ROOT_PASSWORD: pass
        MINIO_PORT_2: 0000
        MINIO_PORT: 0000
        MINIO_HOST: pass
        ELASTIC_VERSION: pass
        ELASTIC_USERNAME: pass
        ELASTIC_PASSWORD: pass
        ELASTIC_PORT: 0000
        ELASTIC_TCP_PORT: 0000
        ELASTIC_HOST: pass
        KIBANA_PORT: 0000
        KIBANA_SYSTEM_PASSWORD: pass
    - name: Cancel workflow on failure
      uses: styfle/cancel-workflow-action@0.8.0
      if: failure()
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
